### ISSUE TITLE
Error message:Cannot read property DatabaseObject of undefined

### ISSUE THREAD

**Issue by JasonYinH** [liyufengrex/HarmonyAtomicService#1]
![image](https://github.com/user-attachments/assets/03abb2cd-39a4-48ad-8bd7-2059003b7925)

**Comment by liyufengrex** [comment]
我的 IDE 版本是 DevEco Studio NEXT Developer Beta3 ，Build Version: 5.0.3.600。我这跑没问题，我看 cloudDatabase 模块的起始版本是 5.0.0（12）。

**Comment by JasonYinH** [comment]
DevEco Studio NEXT Developer Beta5
Build #DS-233.14475.28.36.503700
Build Version: 5.0.3.700, built on August 19, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  documentation.show.toolbar=true
  idea.plugins.compatible.build=IC-233.14475.28
Non-Bundled Plugins:
  com.yanftch.JsonFormat (1.0.8)
  com.intellij.marketplace (233.14475.74)
  com.huawei.deveco.intelligent-assistant (0.408.3)
  com.huawei.cangjie-support-plugin (5.0.3.500)
  izhangzhihao.rainbow.brackets (2024.2.6-233)
  cn.yiiguxing.plugin.translate (3.6.4)

**Comment by JasonYinH** [comment]
那就不太清楚了

**Comment by skyyanyujiangnan** [comment]
一样的问题
HarmonyOS NEXT Developer Beta5 SDK, based on OpenHarmony SDK Ohos_sdk_public 5.0.0.60 (API Version 12 Beta5)

**Comment by JasonYinH** [comment]
我现在好了，不清楚
